### PR TITLE
Pull commits from upstream

### PR DESCRIPTION
**Pull request by aschereT**
Pull in updates from upstream to try and see if that will fix the memory issue

PolicyReporter/requests#5534

---
This change is [Reviewable](https://reviewable.io/reviews/policyreporter/tabula-java/5)

### CODE REVIEW

**Review by Diane-Rose22 — CHANGES_REQUESTED** [review]
Running the test suit - the PolicyReporter added test - testLatticeModeWithColumnAndMultipleAreasOption fails on my system.

> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/policyreporter/tabula-java/5#-:-M741hHNE47fmV6vFJ7H:b-kjajw8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Diane-Rose22 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/policyreporter/tabula-java/5)* status: all files reviewed, 1 unresolved discussion (waiting on @aschereT)

*[a discussion](https://reviewable.io/reviews/policyreporter/tabula-java/5#-M743Zch-UzaEEakQI6S:-M743Zci73X-FZgKqKyJ:b-2q6wvt) (no related file):*
didnt mean to approve

---

**Comment by aschereT** [comment]
Yep, tests failing `mvn test -Dgpg.skip=true -Dtest=TestCommandLineApp`

**Comment by aschereT** [comment]
Closing this PR. A new PR using branches will be made.

**Pull request closed without merging**
